### ISSUE TITLE
VCTF-charter definition issue

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/webpayments-ig#45]
The definition of verifiable claim is too generic and non-specific, so that a
SAML assertion fits this definition. Is that the intention?

If not, then there should be something in the definition about the free
standing nature of the claim, that it is transportable, independent etc
(i.e. self-sovereign without using the term is it is deemed unacceptable)

**Comment by msporny** [comment]
@David-Chadwick would it be acceptable if we added the following to the definition of verifiable claim:

"There is a very strong desire to ensure that verifiable claims support self-sovereign design principles to ensure the utmost flexibility in the usage of these claims."

... or something to that effect. Please word smith as you feel appropriate.

**Comment by David-Chadwick** [comment]
If we go with a definition of verifiable claims that includes
self-sovereign, then we need to have a definition for self-sovereign as
well.

We could have a very simple definition for verifiable claims, such as

verifiable claims are self-sovereign credentials

the definition of Credentials can be found in normal dictionaries e.g.
evidence of authority, status, rights, entitlement to privileges, or the
like (taken from dictionary.com)

Self-sovereign: I dont know what the usual definition of this is, but
searching the internet I have developed a definition based on
https://medium.com/learning-machine-blog/identity-and-digital-self-sovereignty-1f3faab7d9e3

self-sovereign [credential]: confers the [credential] owner with
administrative autonomy [of the credential] regardless of its location
in digital space

I will leave it to others to suggest a better definition for our context
of use.

regards

David

**Comment by msporny** [comment]
> If we go with a definition of verifiable claims that includes self-sovereign, then we need to have a definition for self-sovereign as well.

We already have a definition for self-sovereign in the motivation document:

http://w3c.github.io/webpayments-ig/VCTF/charter/charter-motivation.html#terminology

That is the definition that we have consensus on in the group.

You may be thinking about the removal of the self-sovereign definition from the charter. We move it from the charter to the motivations document.

**Comment by msporny** [comment]
Closing this issue as it's been overcome by events. @David-Chadwick if you disagree, please open a new issue with your concern. Note that we have repositories specific to Verifiable Claims now:

https://github.com/opencreds/vc-data-model/issues
https://github.com/opencreds/vc-use-cases/issues
