### ISSUE TITLE
VCTF charter motivation definition issue

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/webpayments-ig#46]
The  charter motivation document 

http://w3c.github.io/webpayments-ig/VCTF/charter/charter-motivation.html

does not contain the definition for privacy-enhancing, even though it was agreed to add it in our email discussions and telecon a couple of months ago. The definition I gleaned from the discussion was something like:

Privacy-enhancing: the credentials are not required to contain correlating identifiers and they allow the subject to limit the verifiable exposure of information from the credential to specific processors and for specific periods of time.

**Comment by msporny** [comment]
> privacy-enhancing

Would you be okay with this change?

privacy-enhancing: A design principle that strives to empower entities to reduce or eliminate being tracked, being correlated, and enables the subject to limit exposure of information to specific entities or specific periods of time.

**Comment by David-Chadwick** [comment]
Yes fine,

thanks

David

**Comment by msporny** [comment]
This was done here: https://github.com/w3c/webpayments-ig/commit/552c9dced285c55485858a36e4fc09802381f844
